In [2]:
import numpy as np

In [3]:
# create a 1 dimentional array
my1dArray = np.array([1,2,3])
print(my1dArray)


[1 2 3]


In [4]:
# create a 2d array
my2dArray = np.array([[1,2,3], [4,5,6]])
print(my2dArray)

[[1 2 3]
 [4 5 6]]


In [5]:
# creating an array specifying the data type

my2dArrayFloat = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print(my2dArrayFloat)


[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# confirming a data type
my2dArrayFloat.dtype

dtype('float64')

In [7]:
# creating a 2d array with data type in another form

my2dArrayFloat32 = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
print(my2dArrayFloat32)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
# confirming a data type
my2dArrayFloat32.dtype

dtype('float16')

In [9]:
# creating an array with multiple data types

charArray1 = np.array([(1,'aaaaa',4),(4,5,'zzzzz')], dtype='U6')

print(charArray1)

[['1' 'aaaaa' '4']
 ['4' '5' 'zzzzz']]


In [10]:
charArray1.dtype

dtype('<U6')

In [11]:
# create an array
# indicate data ype to the array
# and print the array and print the dtype

charArray2 = np.array ([['a','b',1], ['c','d', '2']],dtype='U1')
print(charArray2)
charArray2.dtype

[['a' 'b' '1']
 ['c' 'd' '2']]


dtype('<U1')

In [12]:
# numpy initialisation
number_rows = 2
number_columns = 3

#creating arrays
array0s = np.zeros([number_rows, number_columns], dtype='int')
print(array0s)

[[0 0 0]
 [0 0 0]]


In [13]:
# create arrays of one

array1s = np.ones([number_rows, number_columns], dtype='float16')
print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# create arrays of 5

array5s = 5 * np.ones((number_rows, number_columns), dtype='float16')
print(array5s)

[[5. 5. 5.]
 [5. 5. 5.]]


In [15]:
array7s = np.full((number_rows, number_columns), 10)
print(array7s)

[[10 10 10]
 [10 10 10]]


In [16]:
# creating an array of evenly spaced values

start = 10
end = 26
step = 3

evenlyStep = np.arange(start, end, step)
print(evenlyStep)

[10 13 16 19 22 25]


In [17]:
# create an array with linspace
# get the number of samples

number_samples = 4
evenlySample = np.linspace(start, end, number_samples, dtype='int')

print(evenlySample)

[10 15 20 26]


In [18]:
# creata an identity matrix
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# generate numbers between 0.0, 1.0
random01 = np.random.random((2,3))
print(random01)

[[0.00529482 0.30024471 0.31039465]
 [0.08410002 0.83272294 0.50136845]]


In [20]:
# generate int between 0,10 - 2 by 3 array
# the last number not included
randomnum = np.random.randint(0,11, (2,3))
print(randomnum)

[[ 9  7 10]
 [ 3 10  6]]


In [21]:
minval = 10.5
maxval = 25.5

In [22]:
randomFloat = np.random.uniform(minval, maxval, (2,3))
print(randomFloat)

[[19.38367685 13.94114947 24.43463222]
 [14.11032844 21.07039903 18.09971745]]


In [23]:
# array inspection, indexing and slicing
a = np.array([[1,2,4],[4,5,6]])

#find the dimension of the array
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Tye:", a.dtype)


Dimension: 2
Shape: (2, 3)
Size: 6
Data Tye: int64


In [24]:
print(a)

[[1 2 4]
 [4 5 6]]


In [25]:
# inspection the array

print(a[1,2])



6


In [26]:
a[0:2, 1]

array([2, 5])

In [27]:
a[a<3]

array([1, 2])

In [28]:
# diagonal
b = np.array([[5,6,7],[1,4,5],[2,3,4]])
print(b)

[[5 6 7]
 [1 4 5]
 [2 3 4]]


In [29]:
np.diag(b)

array([5, 4, 4])

In [30]:
# generate a numpy array
arr = np.array([0,2,4,5,3,7,8,9,5,1])

# find the odd number and replace them with their negative value, but for numbers below 7
arr[(arr % 2 == 1) & (arr < 7)] = -1 * arr[(arr % 2 == 1) & (arr < 7)]

print(arr)

# print the output only when they are below 7
print(arr[arr < 7])



[ 0  2  4 -5 -3  7  8  9 -5 -1]
[ 0  2  4 -5 -3 -5 -1]


In [31]:
# arithmetrics
a = np.array([[1,2,5], [7,1,3]])
b = np.array([[4,6,9], [2,5,9]])



In [32]:
# addition of array

add1 = a + b
add2 = np.add(a,b)

print(add1)
print(add2)

[[ 5  8 14]
 [ 9  6 12]]
[[ 5  8 14]
 [ 9  6 12]]


In [33]:
# subtract

sub1 = a - b
sub2 = np.subtract(a,b)
print(sub1)
print(sub2)


[[-3 -4 -4]
 [ 5 -4 -6]]
[[-3 -4 -4]
 [ 5 -4 -6]]


In [34]:
# multiplication of array
mul1 = a * b
mul2 = np.multiply(a,b)

print(mul1)
print(mul2)


[[ 4 12 45]
 [14  5 27]]
[[ 4 12 45]
 [14  5 27]]


In [35]:
# division
div1 = a/b
div2 = np.divide(a,b)

print(div1)
print(div2)


[[0.25       0.33333333 0.55555556]
 [3.5        0.2        0.33333333]]
[[0.25       0.33333333 0.55555556]
 [3.5        0.2        0.33333333]]


In [36]:
# other operation
# exponential
ex = np.exp(a)
# square root
sqroot = np.sqrt(a)
# sine
find_si = np.sin(a)
find_co = np.cos(a)
find_lg = np.log(a)

# print all the results
print(ex)




[[   2.71828183    7.3890561   148.4131591 ]
 [1096.63315843    2.71828183   20.08553692]]


In [37]:
print(sqroot)

[[1.         1.41421356 2.23606798]
 [2.64575131 1.         1.73205081]]


In [38]:
print(find_si)

[[ 0.84147098  0.90929743 -0.95892427]
 [ 0.6569866   0.84147098  0.14112001]]


In [39]:
print(find_co)

[[ 0.54030231 -0.41614684  0.28366219]
 [ 0.75390225  0.54030231 -0.9899925 ]]


In [40]:
print(find_lg)

[[0.         0.69314718 1.60943791]
 [1.94591015 0.         1.09861229]]


In [41]:
a.shape

(2, 3)

In [42]:
b.shape

(2, 3)

In [43]:
c = np.array([[5,6],[3,5],[8,2]])
c.shape


(3, 2)

In [44]:
# dot product calculations
dotp = a.dot(c)
print(dotp)

[[51 26]
 [62 53]]


In [45]:
# statistics for this array
d = np.array([[1,2,5],[7,1,3]])
# summ
summ1 = a.sum()
summ2 = np.sum(a)

print(summ1)
print(summ2)



19
19


In [46]:
print(d)

[[1 2 5]
 [7 1 3]]


In [47]:
# sum of array column
sum1row = d.sum(axis = 1)
sum2row = np.sum(d, axis=0)

print(sum1row)

[ 8 11]


In [48]:
# maximum overall 
maxi = d.max(axis = 1)
print(maxi)

[5 7]


In [49]:
# mean
average = np.mean(d, axis = 1)
print(average)

[2.66666667 3.66666667]


In [50]:
# standard deviation
stand_dev = np.std(d, axis = 1)
print(stand_dev)

[1.69967317 2.49443826]


In [51]:
# task 1
from numpy import linalg as la
A = np.array([0,0])
B = np.array([0,3])
C = np.array([1.5,0])


In [52]:
# compute
AB = la.norm(A-B)
AC = la.norm(A-C)
BC = la.norm(B-C)

In [53]:
print(AB)

3.0


In [54]:
print(AC)

1.5


In [55]:
print(BC)

3.3541019662496847


In [56]:
# array manipulations
e = np.array([[1,2,5], [7,1,3]])
print(e)
# transpose (row becomes the column and column becomes the row)
# k,l becomes l,k



[[1 2 5]
 [7 1 3]]


In [57]:
# flipping axes where the row becomes columns and columns becomes rows
tr1 = np.transpose(a)
tr2 = e.T

print(tr1)
print(tr2)

[[1 7]
 [2 1]
 [5 3]]
[[1 7]
 [2 1]
 [5 3]]


In [58]:
# reshape an array
print(e)
reshape1 = np.reshape(e, (3,2))
reshape2 = e.reshape(3,2)
print(reshape1)
print(reshape2)

[[1 2 5]
 [7 1 3]]
[[1 2]
 [5 7]
 [1 3]]
[[1 2]
 [5 7]
 [1 3]]


In [59]:
# reshape to rows
reshrow = e.reshape(6)
print(reshrow)



[1 2 5 7 1 3]


In [60]:
print(e)
# horizontal stacking first
f = np.array([[7,8],[4,1]])
g = np.array([[9], [9]])

# hstack
efg = np.hstack([e,f,g])
print(efg)

[[1 2 5]
 [7 1 3]]
[[1 2 5 7 8 9]
 [7 1 3 4 1 9]]


In [61]:
print(e)
# vertical stacking
i = np.array([3,4,1])
j = np.array([[4,4,4], [7,7,7]])

# vertical stacking
eij = np.vstack([e,i,j])
print(eij)



[[1 2 5]
 [7 1 3]]
[[1 2 5]
 [7 1 3]
 [3 4 1]
 [4 4 4]
 [7 7 7]]


In [62]:
x = np.array([[1,2,5], [7,1,3]])
y = np.array([[7,8], [4,1]])

# save an array to a binary file (.npy)
np.save('array_a', x)

In [63]:
# save several arrays to file (default file extension is .npz)
np.savez('array_xv', arr1 = x, arr2 = y)




In [64]:
# save an array in a text file (.txt)
np.savetxt('array_x.txt', x)

In [65]:
# save to a text file but indicate a seperator and the data type we want
# %d means int
# %s means string
# %f means float

np.savetxt('array_x.txt', x, delimiter=',', fmt='%.2f')
np.savetxt('array_x2.txt', x, delimiter=',', fmt='%.2f')
np.savetxt('array_x3.txt', x, delimiter=',', fmt='%s')

In [66]:
# save to a csv file
np.savetxt('array_x4.csv', y, delimiter=',', fmt='%d')

In [67]:
# loading the .npy file
ANPY = np.load('array_a.npy')

# load the array in the .npz file
content = np.load('array_xv.npz')

file1 = content['arr1']
file2 = content['arr2']

# open the .txt file

atx2 = np.loadtxt('array_x3.txt', delimiter= ',', dtype=int)

# read the csv file
acsv = np.loadtxt('array_x4.csv', delimiter= ',', dtype=int)

print(ANPY)
print(atx2)
print(acsv)


[[1 2 5]
 [7 1 3]]
[[1 2 5]
 [7 1 3]]
[[7 8]
 [4 1]]


In [68]:
## create array
data = np.array([[1.99, 2.23], [7.75, 1.89], [3.50, 4.77]])
print(data)

# rounding the array to 1 decimal place and convertin to a string
round_data = np.round(data, 1).astype(str)
print(round_data)

# creata a row header and join it with the array
row_header = np.array([['r1'], ['r2'], ['r3']])

data_with_row_header = np.hstack((row_header, round_data))

print(data_with_row_header)

# adding column header to the  data
column_header = ['c1', 'c2', 'c3']
header = ','.join(column_header)


# save the data in a csv file
np.savetxt('result.csv', data_with_row_header, delimiter=',', fmt='%s', header=header, comments='')



[[1.99 2.23]
 [7.75 1.89]
 [3.5  4.77]]
[['2.0' '2.2']
 ['7.8' '1.9']
 ['3.5' '4.8']]
[['r1' '2.0' '2.2']
 ['r2' '7.8' '1.9']
 ['r3' '3.5' '4.8']]


In [70]:
p = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (p)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [71]:
# get specific element
p[0,0]

np.int64(1)

In [72]:
# replace 3rd column of both of the numpy arrays to 20

p[:,2] = 20

print(p)

[[ 1  2 20  4  5  6  7]
 [ 8  9 20 11 12 13 14]]


In [79]:
# All is matrix
np.full((2,2),99)


array([[99, 99],
       [99, 99]])

In [83]:
# same shape as p
np.full(p.shape, 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [85]:
# same shape as p
np.full_like(p,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [90]:
#random decimal numbers : same shape as p
np.random.random_sample(p.shape)

array([[0.41327691, 0.50340531, 0.80406494, 0.33786308, 0.60877875,
        0.85167702, 0.01758362],
       [0.55179911, 0.97815546, 0.49977139, 0.49074545, 0.39560345,
        0.48926924, 0.19515652]])

In [105]:
#random interger values
# random number between 2 and 3 
np.random.randint(2,4, size= (3,3))

array([[2, 3, 2],
       [2, 2, 3],
       [2, 2, 3]])

In [106]:
# The identitiy matrix (5x 5)

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])