In [3]:
import numpy as np

In [4]:
# create a 1 dimentional array
my1dArray = np.array([1,2,3])
print(my1dArray)


[1 2 3]


In [5]:
# create a 2d array
my2dArray = np.array([[1,2,3], [4,5,6]])
print(my2dArray)

[[1 2 3]
 [4 5 6]]


In [6]:
# creating an array specifying the data type

my2dArrayFloat = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print(my2dArrayFloat)


[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# confirming a data type
my2dArrayFloat.dtype

dtype('float64')

In [8]:
# creating a 2d array with data type in another form

my2dArrayFloat32 = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
print(my2dArrayFloat32)

[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
# confirming a data type
my2dArrayFloat32.dtype

dtype('float16')

In [10]:
# creating an array with multiple data types

charArray1 = np.array([(1,'aaaaa',4),(4,5,'zzzzz')], dtype='U6')

print(charArray1)

[['1' 'aaaaa' '4']
 ['4' '5' 'zzzzz']]


In [11]:
charArray1.dtype

dtype('<U6')

In [12]:
# create an array
# indicate data ype to the array
# and print the array and print the dtype

charArray2 = np.array ([['a','b',1], ['c','d', '2']],dtype='U1')
print(charArray2)
charArray2.dtype

[['a' 'b' '1']
 ['c' 'd' '2']]


dtype('<U1')

In [13]:
# numpy initialisation
number_rows = 2
number_columns = 3

#creating arrays
array0s = np.zeros([number_rows, number_columns], dtype='int')
print(array0s)

[[0 0 0]
 [0 0 0]]


In [14]:
# create arrays of one

array1s = np.ones([number_rows, number_columns], dtype='float16')
print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# create arrays of 5

array5s = 5 * np.ones((number_rows, number_columns), dtype='float16')
print(array5s)

[[5. 5. 5.]
 [5. 5. 5.]]


In [16]:
array7s = np.full((number_rows, number_columns), 10)
print(array7s)

[[10 10 10]
 [10 10 10]]


In [17]:
# creating an array of evenly spaced values

start = 10
end = 26
step = 3

evenlyStep = np.arange(start, end, step)
print(evenlyStep)

[10 13 16 19 22 25]


In [18]:
# create an array with linspace
# get the number of samples

number_samples = 4
evenlySample = np.linspace(start, end, number_samples, dtype='int')

print(evenlySample)

[10 15 20 26]


In [19]:
# creata an identity matrix
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# generate numbers between 0.0, 1.0
random01 = np.random.random((2,3))
print(random01)

[[0.42046553 0.86196553 0.78653673]
 [0.02732815 0.8415738  0.44854287]]


In [21]:
# generate int between 0,10 - 2 by 3 array
# the last number not included
randomnum = np.random.randint(0,11, (2,3))
print(randomnum)

[[10  9  0]
 [ 3 10  3]]


In [22]:
minval = 10.5
maxval = 25.5

In [23]:
randomFloat = np.random.uniform(minval, maxval, (2,3))
print(randomFloat)

[[24.12647194 12.65936924 24.4011153 ]
 [12.12147631 20.74792815 18.01766849]]


In [24]:
# array inspection, indexing and slicing
a = np.array([[1,2,4],[4,5,6]])

#find the dimension of the array
print("Dimension:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Tye:", a.dtype)


Dimension: 2
Shape: (2, 3)
Size: 6
Data Tye: int64


In [25]:
print(a)

[[1 2 4]
 [4 5 6]]


In [26]:
# inspection the array

print(a[1,2])



6


In [27]:
a[0:2, 1]

array([2, 5])

In [28]:
a[a<3]

array([1, 2])

In [29]:
# diagonal
b = np.array([[5,6,7],[1,4,5],[2,3,4]])
print(b)

[[5 6 7]
 [1 4 5]
 [2 3 4]]


In [30]:
np.diag(b)

array([5, 4, 4])

In [31]:
# generate a numpy array
arr = np.array([0,2,4,5,3,7,8,9,5,1])

# find the odd number and replace them with their negative value, but for numbers below 7
arr[(arr % 2 == 1) & (arr < 7)] = -1 * arr[(arr % 2 == 1) & (arr < 7)]

print(arr)

# print the output only when they are below 7
print(arr[arr < 7])



[ 0  2  4 -5 -3  7  8  9 -5 -1]
[ 0  2  4 -5 -3 -5 -1]


In [35]:
# multiplying the arrays
a = np.array([1,3,5])
b = np.array([1,2,3])

a*b

array([ 1,  6, 15])