In [1]:
import numpy as np

In [2]:
# create a 1 dimentional array
my1dArray = np.array([1,2,3])
print(my1dArray)


In [5]:
# create a 2d array
my2dArray = np.array([[1,2,3], [4,5,6]])
print(my2dArray)

[[1 2 3]
 [4 5 6]]


In [7]:
# creating an array specifying the data type

my2dArrayFloat = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print(my2dArrayFloat)


[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
# confirming a data type
my2dArrayFloat.dtype

dtype('float64')

In [15]:
# creating a 2d array with data type in another form

my2dArrayFloat32 = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
print(my2dArrayFloat32)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
# confirming a data type
my2dArrayFloat32.dtype

dtype('float16')

In [26]:
# creating an array with multiple data types

charArray1 = np.array([(1,'aaaaa',4),(4,5,'zzzzz')], dtype='U6')

print(charArray1)

[['1' 'aaaaa' '4']
 ['4' '5' 'zzzzz']]


In [25]:
charArray1.dtype

dtype('<U4')

In [27]:
# create an array
# indicate data ype to the array
# and print the array and print the dtype

charArray2 = np.array ([['a','b',1], ['c','d', '2']],dtype='U1')
print(charArray2)
charArray2.dtype

[['a' 'b' '1']
 ['c' 'd' '2']]


dtype('<U1')

In [31]:
# numpy initialisation
number_rows = 2
number_columns = 3

#creating arrays
array0s = np.zeros([number_rows, number_columns], dtype='int')
print(array0s)

[[0 0 0]
 [0 0 0]]


In [33]:
# create arrays of one

array1s = np.ones([number_rows, number_columns], dtype='float16')
print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [48]:
# create arrays of 5

array5s = 5 * np.ones((number_rows, number_columns), dtype='float16')
print(array5s)

[[5. 5. 5.]
 [5. 5. 5.]]


In [49]:
array7s = np.full((number_rows, number_columns), 10)
print(array7s)

[[10 10 10]
 [10 10 10]]


In [51]:
# creating an array of evenly spaced values

start = 10
end = 26
step = 3

evenlyStep = np.arange(start, end, step)
print(evenlyStep)

[10 13 16 19 22 25]


In [52]:
# create an array with linspace
# get the number of samples

number_samples = 3
evenlySample = np.linspace(start, end, number_samples)

print(evenlySample)

[10. 18. 26.]
